http:
  middlewares:
    umami:
      plugin:
        traefik-umami-plugin:
          forwardPath: umami
          umamiHost: http://umami:3000
          websiteId: "798edb2f-b009-497b-bf5b-f3d7c6c8dc05"

    plain-to-html-body:
      plugin:
        rewrite-body:
          lastModified: true
          rewrites:
            - regex: \n
              replacement: "$1<br>"
            - regex: ([\S\s]*)
              replacement: "<!DOCTYPE html><html><head></head><body>$1</body></html>"
          monitor:
            types:
              - text/plain

    plain-to-html-header:
      headers:
        customResponseHeaders:
          Content-Type: "text/html"

    compress:
      compress: true
          
    plain-to-html:
      chain:
        middlewares:
          - plain-to-html-header
          - plain-to-html-body
          - compress