log:
  level: INFO

# accessLog: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-umami-plugin
    watch: true
  file:
    directory: /config
    watch: true

entryPoints:
  "traefik": # traefik dashboard
    address: ":8080"
  "whoami": # http
    address: ":8081"
  "umami": # umami dashboard
    address: ":3000"

api:
  dashboard: true

experimental:
  localPlugins:
    traefik-umami-plugin:
      moduleName: "github.com/1cedsoda/traefik-umami-plugin"
  plugins:
    rewrite-body:
      moduleName: "github.com/packruler/rewrite-body"
      version: "v1.2.0" 